# Generated by Django 4.2.5 on 2023-11-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0003_alter_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
