# Generated by Django 4.2.5 on 2023-11-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Username',
        ),
    ]
