# Generated by Django 4.2.5 on 2023-11-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0006_remove_post_user_post_username_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(help_text='Post content', max_length=3000, verbose_name='text')),
                ('thread', models.ManyToManyField(to='imageboard.thread')),
            ],
            options={
                'db_table': 'Headliner',
            },
        ),
    ]
