# Generated by Django 4.2.5 on 2023-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shortcut',
            field=models.CharField(blank=True, help_text="Shortcut's name", max_length=5, null=True, verbose_name='Shortcut'),
        ),
    ]
