# Generated by Django 4.2.5 on 2023-11-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_board_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(help_text='Post content', max_length=3000, verbose_name='text'),
        ),
    ]
