# Generated by Django 4.2.5 on 2023-12-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_headliner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headliner',
        ),
    ]
