# Generated by Django 5.0.4 on 2024-04-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='responsible',
            field=models.ForeignKey(help_text='ФИО Ответственного', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
