# Generated by Django 5.0.4 on 2024-04-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_password_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DBUser',
        ),
    ]
